http:
  listener:
    host: "localhost"
    port: "8081"
    path: "/travelontipcall/{serviceType}"
    
db:
  Host: "localhost"
  Port: "1522"
  User: "system"
  Password: "123"
  Instance: "orcl"
 
  
  