http:
  listener:
    host: "localhost"
    port: "8081"
    path: "/travelontipcall/{serviceType}"
    
db:
  oracle:
    host: "localhost"
    port: "1522"
    user: "system"
    password: "123"
    Instance: "orcl"
 
  
  